// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"bitbucket.org/yesboss/sharingan/common"
	"bitbucket.org/yesboss/sharingan/config"
	"bitbucket.org/yesboss/sharingan/controller"
	"bitbucket.org/yesboss/sharingan/delivery/grpc"
	"bitbucket.org/yesboss/sharingan/delivery/http"
	"bitbucket.org/yesboss/sharingan/repo"
)

import (
	_ "database/sql"
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeContainer() (App, error) {
	configConfig := config.New()
	db, err := common.NewMysqlConnection()
	if err != nil {
		return App{}, err
	}
	userRepo, err := repo.NewUserRepo(configConfig, db)
	if err != nil {
		return App{}, err
	}
	userController := controller.NewUserController(configConfig, userRepo)
	expenseRepo, err := repo.NewExpenseRepo(configConfig, db)
	if err != nil {
		return App{}, err
	}
	expenseController := controller.NewExpenseController(configConfig, expenseRepo)
	echo := http.New(userController, expenseController)
	server := grpc.New(userController)
	app := newApp(configConfig, echo, server)
	return app, nil
}
